preserve_hierarchy: true
files:
  - source: /osu.Game.Rulesets.Karaoke/Localisation/*.resx
    translation: /osu.Game.Rulesets.Karaoke/Localisation/%file_name%.%locale%.%file_extension%
    ignore:
      - /osu.Game.Rulesets.Karaoke/Localisation/%file_name%.*.%file_extension%
    update_option: update_as_unapproved
    languages_mapping:
      locale:
        ja: ja
        zh-CN: zh
        zh-TW: zh-Hant
